package CHAINE;

import java.io.Serializable;

public class Noeud implements Serializable{

	private static final long serialVersionUID = 1L; //Auto-generated by eclipse
	
	public int px;
	public int p999;
	
	public Noeud(int a, int b)
	{
		px = a;
		p999 = b;
	}

	
	
	
	
	
}